import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Receipt, User } from '@common/types';

export const PDFService = {
    generateLegalReport: (receipts: Receipt[], user: User | null, dateRange: { start: Date; end: Date }) => {
        const doc = new jsPDF();

        // --- Header ---
        doc.setFontSize(20);
        doc.setTextColor(40, 40, 40);
        doc.text('Expense Report', 14, 22);

        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30);

        if (user) {
            doc.text(`Prepared for: ${user.name} (${user.email})`, 14, 35);
        }

        doc.text(`Period: ${dateRange.start.toLocaleDateString()} - ${dateRange.end.toLocaleDateString()}`, 14, 40);

        // --- Summary Calculation ---
        let totalAmount = 0;
        let childRelatedAmount = 0;
        let totalItems = 0;

        // Filter receipts within range
        const filteredReceipts = receipts.filter(r => {
            const rDate = new Date(r.date);
            return rDate >= dateRange.start && rDate <= dateRange.end;
        });

        filteredReceipts.forEach(r => {
            totalAmount += r.total;
            r.items.forEach(i => {
                totalItems++;
                if (i.isChildRelated) {
                    childRelatedAmount += i.price;
                }
            });
        });

        // --- Summary Table ---
        autoTable(doc, {
            startY: 50,
            head: [['Summary Metric', 'Value']],
            body: [
                ['Total Expenses', `€${totalAmount.toFixed(2)}`],
                ['Child Related Expenses', `€${childRelatedAmount.toFixed(2)}`],
                ['Total Transactions', filteredReceipts.length.toString()],
                ['Total Items', totalItems.toString()],
            ],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
            styles: { fontSize: 10, cellPadding: 4 },
        });

        // --- Detailed Transactions ---
        doc.text('Detailed Transactions', 14, (doc as any).lastAutoTable.finalY + 15);

        const tableData = filteredReceipts.map(r => {
            const childItems = r.items.filter(i => i.isChildRelated).map(i => i.name).join(', ');
            const isChildRelated = r.items.some(i => i.isChildRelated);

            return [
                new Date(r.date).toLocaleDateString(),
                r.storeName,
                `€${r.total.toFixed(2)}`,
                isChildRelated ? 'Yes' : 'No',
                childItems || '-'
            ];
        });

        autoTable(doc, {
            startY: (doc as any).lastAutoTable.finalY + 20,
            head: [['Date', 'Store', 'Total', 'Child Related', 'Child Items']],
            body: tableData,
            theme: 'striped',
            headStyles: { fillColor: [41, 128, 185] },
            styles: { fontSize: 9, cellPadding: 3 },
            columnStyles: {
                0: { cellWidth: 25 },
                1: { cellWidth: 40 },
                2: { cellWidth: 25 },
                3: { cellWidth: 25 },
                4: { cellWidth: 'auto' },
            }
        });

        // --- Footer ---
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150, 150, 150);
            doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 20, doc.internal.pageSize.height - 10, { align: 'right' });
            doc.text('Generated by TrueTrack', 14, doc.internal.pageSize.height - 10);
        }

        // Save
        const filename = `TrueTrack_Report_${dateRange.start.toISOString().split('T')[0]}_${dateRange.end.toISOString().split('T')[0]}.pdf`;
        doc.save(filename);
    }
};
